## arsbridge -- example_helpers.R
## ---------------------------------------------------------------------------
## Tiny user-facing helpers that expose the bundled training data and offer a
## zero-argument entry point so new users can see the package do its thing
## without owning a study.
##
## Pattern (intentional): mirrors `readr::readr_example()` and
## `palmerpenguins::path_to_file()` -- when called with no argument, list
## available files; when called with a name, return the absolute path.

#' Bundled training files shipped with arsbridge
#'
#' Returns the absolute path to a bundled example file, or -- when called
#' with no argument -- the names of all files available in the bundle.
#' The bundle is the CDSC-ALZ-201 training study: a synthetic Alzheimer's
#' disease study built entirely from public material. The datasets are the
#' CDISC pilot Xanomeline data as packaged by `{pharmaverseadam}`
#' (Apache-2.0, no real patient data), and every file is regenerated by
#' `data-raw/build_example_bundle.R` in the package source.
#'
#' @param file Character. Name of a bundled file (e.g.
#'   `"annotated_shell.docx"`). If `NULL` (default), returns a character
#'   vector of every file in the bundle.
#'
#' @return A character path (absolute) when `file` is named; a character
#'   vector of file names when `file` is `NULL`.
#'
#' @details
#' Files currently in the bundle:
#' \describe{
#'   \item{`annotated_shell.docx`}{Lead-programmer annotated TLF shells for
#'     8 outputs (5 tables, 2 listings, 1 figure), in Word. Uses the
#'     standard red \code{C00000} run convention for ADaM variable
#'     references. Roughly 97 KB.}
#'   \item{`annotated_shell.xlsx`}{The Excel counterpart: one annotated
#'     worksheet per output (two tables, a listing, a figure). This is the
#'     shell [ars_fill_shell()] can write back filled, so the bundle demos
#'     the whole chain offline. Roughly 10 KB.}
#'   \item{`adam_spec.xlsx`}{ADaM specification workbook covering the 5
#'     domains the shells reference (ADSL, ADAE, ADEX, ADCM, ADVS; 123
#'     variables), with labels and types taken from the pharmaverseadam
#'     column metadata, plus codelists for the decoded categories
#'     (SEX, AESEV, ASEV, AESER). Roughly 16 KB.}
#'   \item{`ADaM.zip`}{The five pharmaverseadam datasets as XPT files,
#'     restricted to the curated variables; ADVS keeps only
#'     \code{PARAMCD = 'PULSE'}, the one parameter the shells read.
#'     Roughly 265 KB compressed. Unzip and pass the folder as
#'     `adam_dir` to [ars_to_ard()].}
#' }
#'
#' @examples
#' arsbridge_example()                       # list bundle contents
#' arsbridge_example("annotated_shell.docx") # path to the Word shell
#' arsbridge_example("annotated_shell.xlsx") # path to the Excel shell
#' arsbridge_example("adam_spec.xlsx")       # path to the ADaM spec
#'
#' @export
arsbridge_example <- function(file = NULL) {
  bundle <- system.file("extdata", "example_cdsc_alz_201",
                        package = "arsbridge")
  if (!nzchar(bundle) || !dir.exists(bundle)) {
    cli::cli_abort(c(
      "arsbridge example bundle not found.",
      "i" = "Reinstall the package or run {.code devtools::load_all()} from the package source."
    ))
  }

  files <- list.files(bundle)
  if (is.null(file)) return(files)

  if (!file %in% files) {
    cli::cli_abort(c(
      "{.val {file}} is not in the bundle.",
      "i" = "Available: {.val {files}}",
      " " = "Call {.code arsbridge_example()} with no argument to list bundle contents."
    ))
  }

  file.path(bundle, file)
}


#' Run spec_to_ars() against the bundled example inputs
#'
#' Zero-argument entry point that runs the full `spec_to_ars()` pipeline
#' against the bundled CDSC-ALZ-201 shell and ADaM spec. Useful as a first
#' call after installation -- you get a real ARS JSON and validation report
#' from the training shell without owning a study.
#'
#' @param output_path Where to write the ARS JSON. Default:
#'   `"reporting_event.json"` in `tempdir()`.
#' @param report_path Where to write the spec validation report. Default:
#'   `"spec_validation_report.xlsx"` in `tempdir()`.
#' @param shell_format Which bundled shell to read: `"docx"` (default, all
#'   8 outputs) or `"xlsx"` (the Excel worksheets -- the shell that
#'   [ars_fill_shell()] can write back filled).
#' @param ... Additional arguments forwarded to [spec_to_ars()].
#'
#' @return Invisibly returns the [spec_to_ars()] result list.
#'
#' @examples
#' \dontrun{
#' # One-call demo. Deterministic (no API key needed); seconds, not minutes.
#' res <- spec_to_ars_example()
#' res$n_tlfs       # 8
#' str(res$reporting_event, max.level = 1)
#' }
#' @export
spec_to_ars_example <- function(
  output_path = file.path(tempdir(), "reporting_event.json"),
  report_path = file.path(tempdir(), "spec_validation_report.xlsx"),
  shell_format = c("docx", "xlsx"),
  ...
) {
  shell_format <- match.arg(shell_format)
  spec_to_ars(
    shell_path     = arsbridge_example(paste0("annotated_shell.",
                                              shell_format)),
    adam_spec_path = arsbridge_example("adam_spec.xlsx"),
    output_path    = output_path,
    report_path    = report_path,
    study_id       = "CDSC-ALZ-201",
    study_name     = "Xanomeline Transdermal System in Mild-to-Moderate Alzheimer's Disease (training example)",
    ...
  )
}
